// src/pages/webcheckin/wciCountries.ts
// Lista completa de países (ISO 3166-1 alpha-2) para os selects do Web Check-in.
// Os mais frequentes ficam no topo; o restante em ordem alfabética.

export interface WciCountry { code: string; label: string; }

const PRIORITY: WciCountry[] = [
  { code: 'BR', label: '🇧🇷 Brasil (BR)' },
  { code: 'AR', label: '🇦🇷 Argentina (AR)' },
  { code: 'UY', label: '🇺🇾 Uruguai (UY)' },
  { code: 'PY', label: '🇵🇾 Paraguai (PY)' },
  { code: 'CL', label: '🇨🇱 Chile (CL)' },
  { code: 'BO', label: '🇧🇴 Bolívia (BO)' },
  { code: 'PE', label: '🇵🇪 Peru (PE)' },
  { code: 'CO', label: '🇨🇴 Colômbia (CO)' },
  { code: 'VE', label: '🇻🇪 Venezuela (VE)' },
  { code: 'MX', label: '🇲🇽 México (MX)' },
  { code: 'US', label: '🇺🇸 Estados Unidos (US)' },
  { code: 'PT', label: '🇵🇹 Portugal (PT)' },
  { code: 'ES', label: '🇪🇸 Espanha (ES)' },
  { code: 'FR', label: '🇫🇷 França (FR)' },
  { code: 'IT', label: '🇮🇹 Itália (IT)' },
  { code: 'DE', label: '🇩🇪 Alemanha (DE)' },
  { code: 'GB', label: '🇬🇧 Reino Unido (GB)' },
];

const REST: WciCountry[] = [
  { code: 'AF', label: '🇦🇫 Afeganistão (AF)' },
  { code: 'ZA', label: '🇿🇦 África do Sul (ZA)' },
  { code: 'AL', label: '🇦🇱 Albânia (AL)' },
  { code: 'AD', label: '🇦🇩 Andorra (AD)' },
  { code: 'AO', label: '🇦🇴 Angola (AO)' },
  { code: 'AI', label: '🇦🇮 Anguila (AI)' },
  { code: 'AG', label: '🇦🇬 Antígua e Barbuda (AG)' },
  { code: 'SA', label: '🇸🇦 Arábia Saudita (SA)' },
  { code: 'DZ', label: '🇩🇿 Argélia (DZ)' },
  { code: 'AM', label: '🇦🇲 Armênia (AM)' },
  { code: 'AW', label: '🇦🇼 Aruba (AW)' },
  { code: 'AU', label: '🇦🇺 Austrália (AU)' },
  { code: 'AT', label: '🇦🇹 Áustria (AT)' },
  { code: 'AZ', label: '🇦🇿 Azerbaijão (AZ)' },
  { code: 'BS', label: '🇧🇸 Bahamas (BS)' },
  { code: 'BH', label: '🇧🇭 Bahrein (BH)' },
  { code: 'BD', label: '🇧🇩 Bangladesh (BD)' },
  { code: 'BB', label: '🇧🇧 Barbados (BB)' },
  { code: 'BE', label: '🇧🇪 Bélgica (BE)' },
  { code: 'BZ', label: '🇧🇿 Belize (BZ)' },
  { code: 'BJ', label: '🇧🇯 Benin (BJ)' },
  { code: 'BM', label: '🇧🇲 Bermudas (BM)' },
  { code: 'BY', label: '🇧🇾 Bielorrússia (BY)' },
  { code: 'BA', label: '🇧🇦 Bósnia e Herzegovina (BA)' },
  { code: 'BW', label: '🇧🇼 Botsuana (BW)' },
  { code: 'BN', label: '🇧🇳 Brunei (BN)' },
  { code: 'BG', label: '🇧🇬 Bulgária (BG)' },
  { code: 'BF', label: '🇧🇫 Burquina Faso (BF)' },
  { code: 'BI', label: '🇧🇮 Burundi (BI)' },
  { code: 'BT', label: '🇧🇹 Butão (BT)' },
  { code: 'CV', label: '🇨🇻 Cabo Verde (CV)' },
  { code: 'CM', label: '🇨🇲 Camarões (CM)' },
  { code: 'KH', label: '🇰🇭 Camboja (KH)' },
  { code: 'CA', label: '🇨🇦 Canadá (CA)' },
  { code: 'QA', label: '🇶🇦 Catar (QA)' },
  { code: 'KZ', label: '🇰🇿 Cazaquistão (KZ)' },
  { code: 'TD', label: '🇹🇩 Chade (TD)' },
  { code: 'CN', label: '🇨🇳 China (CN)' },
  { code: 'CY', label: '🇨🇾 Chipre (CY)' },
  { code: 'SG', label: '🇸🇬 Cingapura (SG)' },
  { code: 'KM', label: '🇰🇲 Comores (KM)' },
  { code: 'CG', label: '🇨🇬 Congo (CG)' },
  { code: 'CD', label: '🇨🇩 Congo, Rep. Democrática (CD)' },
  { code: 'KP', label: '🇰🇵 Coreia do Norte (KP)' },
  { code: 'KR', label: '🇰🇷 Coreia do Sul (KR)' },
  { code: 'CI', label: '🇨🇮 Costa do Marfim (CI)' },
  { code: 'CR', label: '🇨🇷 Costa Rica (CR)' },
  { code: 'HR', label: '🇭🇷 Croácia (HR)' },
  { code: 'CU', label: '🇨🇺 Cuba (CU)' },
  { code: 'CW', label: '🇨🇼 Curaçao (CW)' },
  { code: 'DK', label: '🇩🇰 Dinamarca (DK)' },
  { code: 'DJ', label: '🇩🇯 Djibuti (DJ)' },
  { code: 'DM', label: '🇩🇲 Dominica (DM)' },
  { code: 'EG', label: '🇪🇬 Egito (EG)' },
  { code: 'SV', label: '🇸🇻 El Salvador (SV)' },
  { code: 'AE', label: '🇦🇪 Emirados Árabes Unidos (AE)' },
  { code: 'EC', label: '🇪🇨 Equador (EC)' },
  { code: 'ER', label: '🇪🇷 Eritreia (ER)' },
  { code: 'SK', label: '🇸🇰 Eslováquia (SK)' },
  { code: 'SI', label: '🇸🇮 Eslovênia (SI)' },
  { code: 'EE', label: '🇪🇪 Estônia (EE)' },
  { code: 'SZ', label: '🇸🇿 Essuatíni (SZ)' },
  { code: 'ET', label: '🇪🇹 Etiópia (ET)' },
  { code: 'FJ', label: '🇫🇯 Fiji (FJ)' },
  { code: 'PH', label: '🇵🇭 Filipinas (PH)' },
  { code: 'FI', label: '🇫🇮 Finlândia (FI)' },
  { code: 'GA', label: '🇬🇦 Gabão (GA)' },
  { code: 'GM', label: '🇬🇲 Gâmbia (GM)' },
  { code: 'GH', label: '🇬🇭 Gana (GH)' },
  { code: 'GE', label: '🇬🇪 Geórgia (GE)' },
  { code: 'GI', label: '🇬🇮 Gibraltar (GI)' },
  { code: 'GD', label: '🇬🇩 Granada (GD)' },
  { code: 'GR', label: '🇬🇷 Grécia (GR)' },
  { code: 'GL', label: '🇬🇱 Groenlândia (GL)' },
  { code: 'GP', label: '🇬🇵 Guadalupe (GP)' },
  { code: 'GT', label: '🇬🇹 Guatemala (GT)' },
  { code: 'GY', label: '🇬🇾 Guiana (GY)' },
  { code: 'GF', label: '🇬🇫 Guiana Francesa (GF)' },
  { code: 'GN', label: '🇬🇳 Guiné (GN)' },
  { code: 'GW', label: '🇬🇼 Guiné-Bissau (GW)' },
  { code: 'GQ', label: '🇬🇶 Guiné Equatorial (GQ)' },
  { code: 'HT', label: '🇭🇹 Haiti (HT)' },
  { code: 'NL', label: '🇳🇱 Holanda (NL)' },
  { code: 'HN', label: '🇭🇳 Honduras (HN)' },
  { code: 'HK', label: '🇭🇰 Hong Kong (HK)' },
  { code: 'HU', label: '🇭🇺 Hungria (HU)' },
  { code: 'YE', label: '🇾🇪 Iêmen (YE)' },
  { code: 'KY', label: '🇰🇾 Ilhas Cayman (KY)' },
  { code: 'MV', label: '🇲🇻 Ilhas Maldivas (MV)' },
  { code: 'MH', label: '🇲🇭 Ilhas Marshall (MH)' },
  { code: 'VG', label: '🇻🇬 Ilhas Virgens Britânicas (VG)' },
  { code: 'IN', label: '🇮🇳 Índia (IN)' },
  { code: 'ID', label: '🇮🇩 Indonésia (ID)' },
  { code: 'IR', label: '🇮🇷 Irã (IR)' },
  { code: 'IQ', label: '🇮🇶 Iraque (IQ)' },
  { code: 'IE', label: '🇮🇪 Irlanda (IE)' },
  { code: 'IS', label: '🇮🇸 Islândia (IS)' },
  { code: 'IL', label: '🇮🇱 Israel (IL)' },
  { code: 'JM', label: '🇯🇲 Jamaica (JM)' },
  { code: 'JP', label: '🇯🇵 Japão (JP)' },
  { code: 'JO', label: '🇯🇴 Jordânia (JO)' },
  { code: 'KW', label: '🇰🇼 Kuwait (KW)' },
  { code: 'LA', label: '🇱🇦 Laos (LA)' },
  { code: 'LS', label: '🇱🇸 Lesoto (LS)' },
  { code: 'LV', label: '🇱🇻 Letônia (LV)' },
  { code: 'LB', label: '🇱🇧 Líbano (LB)' },
  { code: 'LR', label: '🇱🇷 Libéria (LR)' },
  { code: 'LY', label: '🇱🇾 Líbia (LY)' },
  { code: 'LI', label: '🇱🇮 Liechtenstein (LI)' },
  { code: 'LT', label: '🇱🇹 Lituânia (LT)' },
  { code: 'LU', label: '🇱🇺 Luxemburgo (LU)' },
  { code: 'MO', label: '🇲🇴 Macau (MO)' },
  { code: 'MK', label: '🇲🇰 Macedônia do Norte (MK)' },
  { code: 'MG', label: '🇲🇬 Madagascar (MG)' },
  { code: 'MY', label: '🇲🇾 Malásia (MY)' },
  { code: 'MW', label: '🇲🇼 Malaui (MW)' },
  { code: 'ML', label: '🇲🇱 Mali (ML)' },
  { code: 'MT', label: '🇲🇹 Malta (MT)' },
  { code: 'MA', label: '🇲🇦 Marrocos (MA)' },
  { code: 'MQ', label: '🇲🇶 Martinica (MQ)' },
  { code: 'MU', label: '🇲🇺 Maurício (MU)' },
  { code: 'MR', label: '🇲🇷 Mauritânia (MR)' },
  { code: 'MM', label: '🇲🇲 Mianmar (MM)' },
  { code: 'FM', label: '🇫🇲 Micronésia (FM)' },
  { code: 'MZ', label: '🇲🇿 Moçambique (MZ)' },
  { code: 'MD', label: '🇲🇩 Moldávia (MD)' },
  { code: 'MC', label: '🇲🇨 Mônaco (MC)' },
  { code: 'MN', label: '🇲🇳 Mongólia (MN)' },
  { code: 'ME', label: '🇲🇪 Montenegro (ME)' },
  { code: 'NA', label: '🇳🇦 Namíbia (NA)' },
  { code: 'NP', label: '🇳🇵 Nepal (NP)' },
  { code: 'NI', label: '🇳🇮 Nicarágua (NI)' },
  { code: 'NE', label: '🇳🇪 Níger (NE)' },
  { code: 'NG', label: '🇳🇬 Nigéria (NG)' },
  { code: 'NO', label: '🇳🇴 Noruega (NO)' },
  { code: 'NC', label: '🇳🇨 Nova Caledônia (NC)' },
  { code: 'NZ', label: '🇳🇿 Nova Zelândia (NZ)' },
  { code: 'OM', label: '🇴🇲 Omã (OM)' },
  { code: 'PW', label: '🇵🇼 Palau (PW)' },
  { code: 'PS', label: '🇵🇸 Palestina (PS)' },
  { code: 'PA', label: '🇵🇦 Panamá (PA)' },
  { code: 'PG', label: '🇵🇬 Papua-Nova Guiné (PG)' },
  { code: 'PK', label: '🇵🇰 Paquistão (PK)' },
  { code: 'PL', label: '🇵🇱 Polônia (PL)' },
  { code: 'PF', label: '🇵🇫 Polinésia Francesa (PF)' },
  { code: 'PR', label: '🇵🇷 Porto Rico (PR)' },
  { code: 'KE', label: '🇰🇪 Quênia (KE)' },
  { code: 'KG', label: '🇰🇬 Quirguistão (KG)' },
  { code: 'CF', label: '🇨🇫 República Centro-Africana (CF)' },
  { code: 'DO', label: '🇩🇴 República Dominicana (DO)' },
  { code: 'CZ', label: '🇨🇿 República Tcheca (CZ)' },
  { code: 'RO', label: '🇷🇴 Romênia (RO)' },
  { code: 'RW', label: '🇷🇼 Ruanda (RW)' },
  { code: 'RU', label: '🇷🇺 Rússia (RU)' },
  { code: 'WS', label: '🇼🇸 Samoa (WS)' },
  { code: 'SM', label: '🇸🇲 San Marino (SM)' },
  { code: 'LC', label: '🇱🇨 Santa Lúcia (LC)' },
  { code: 'KN', label: '🇰🇳 São Cristóvão e Névis (KN)' },
  { code: 'ST', label: '🇸🇹 São Tomé e Príncipe (ST)' },
  { code: 'VC', label: '🇻🇨 São Vicente e Granadinas (VC)' },
  { code: 'SC', label: '🇸🇨 Seicheles (SC)' },
  { code: 'SN', label: '🇸🇳 Senegal (SN)' },
  { code: 'SL', label: '🇸🇱 Serra Leoa (SL)' },
  { code: 'RS', label: '🇷🇸 Sérvia (RS)' },
  { code: 'SY', label: '🇸🇾 Síria (SY)' },
  { code: 'SO', label: '🇸🇴 Somália (SO)' },
  { code: 'LK', label: '🇱🇰 Sri Lanka (LK)' },
  { code: 'SD', label: '🇸🇩 Sudão (SD)' },
  { code: 'SS', label: '🇸🇸 Sudão do Sul (SS)' },
  { code: 'SE', label: '🇸🇪 Suécia (SE)' },
  { code: 'CH', label: '🇨🇭 Suíça (CH)' },
  { code: 'SR', label: '🇸🇷 Suriname (SR)' },
  { code: 'TH', label: '🇹🇭 Tailândia (TH)' },
  { code: 'TW', label: '🇹🇼 Taiwan (TW)' },
  { code: 'TJ', label: '🇹🇯 Tajiquistão (TJ)' },
  { code: 'TZ', label: '🇹🇿 Tanzânia (TZ)' },
  { code: 'TL', label: '🇹🇱 Timor-Leste (TL)' },
  { code: 'TG', label: '🇹🇬 Togo (TG)' },
  { code: 'TO', label: '🇹🇴 Tonga (TO)' },
  { code: 'TT', label: '🇹🇹 Trinidad e Tobago (TT)' },
  { code: 'TN', label: '🇹🇳 Tunísia (TN)' },
  { code: 'TM', label: '🇹🇲 Turcomenistão (TM)' },
  { code: 'TR', label: '🇹🇷 Turquia (TR)' },
  { code: 'UA', label: '🇺🇦 Ucrânia (UA)' },
  { code: 'UG', label: '🇺🇬 Uganda (UG)' },
  { code: 'UZ', label: '🇺🇿 Uzbequistão (UZ)' },
  { code: 'VU', label: '🇻🇺 Vanuatu (VU)' },
  { code: 'VA', label: '🇻🇦 Vaticano (VA)' },
  { code: 'VN', label: '🇻🇳 Vietnã (VN)' },
  { code: 'ZM', label: '🇿🇲 Zâmbia (ZM)' },
  { code: 'ZW', label: '🇿🇼 Zimbábue (ZW)' },
];

// Lista final: prioritários + demais em ordem alfabética + fallback 'Outro'
// (mantido por compatibilidade com fichas antigas que salvaram 'OTHER').
export const WCI_COUNTRIES: WciCountry[] = [
  ...PRIORITY,
  ...REST,
  { code: 'OTHER', label: 'Outro' },
];
